### ISSUE TITLE
Error installing apax

### ISSUE THREAD

**Issue by smslule** [apax-hub/apax#382]
PS D:\GitHub_Project\apax> pip install apax
Collecting apax
  Using cached apax-0.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting ase<4.0.0,>=3.22.1 (from apax)
  Using cached ase-3.23.0-py3-none-any.whl.metadata (3.8 kB)
Collecting clu<0.0.8,>=0.0.7 (from apax)
  Using cached clu-0.0.7-py3-none-any.whl.metadata (2.0 kB)
Collecting e3x<2.0.0,>=1.0.2 (from apax)
  Using cached e3x-1.0.2-py3-none-any.whl.metadata (3.6 kB)
Collecting einops<0.7.0,>=0.6.0 (from apax)
  Using cached einops-0.6.1-py3-none-any.whl.metadata (12 kB)
Collecting flax==0.8.4 (from apax)
  Using cached flax-0.8.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: jax<0.5.0,>=0.4.25 in c:\users\administrator\appdata\local\programs\python\python313\lib\site-packages (from apax) (0.4.37)
Collecting lazy-loader<0.5,>=0.4 (from apax)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Collecting numpy<2.0,>=1.23 (from apax)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e\vendored-meson\meson\meson.py setup C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e\.mesonpy-4wcdwwhw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e\.mesonpy-4wcdwwhw\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e    
      Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e\.mesonpy-4wcdwwhw
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output
     
      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `cc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `gcc --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang --version` gave "[WinError 2] 系统找不到指定的文件。"
      Running `clang-cl /?` gave "[WinError 2] 系统找不到指定的文件。"
      Running `pgcc --version` gave "[WinError 2] 系统找不到指定的文件。"
     
      A full log can be found at C:\Users\Administrator\AppData\Local\Temp\pip-install-xsdvulod\numpy_4cff7dcee46b4f8d9a75f02dd9f6153e\.mesonpy-4wcdwwhw\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by M-R-Schaefer** [comment]
Hi, thank you for reaching out. 
It seems that the problem arises due to python not finding a C compiler. I would recommend making sure that you have something like gcc installed and available in your path.
That said, we have no experience with installing Apax on Windows as Jax does not offer GPU support for that plattform.

**Comment by smslule** [comment]
### **The compiler error has been resolved, but a new error has emerged.**

> C:\Users\Administrator>pip install git+https://github.com/apax-hub/apax.git
> Collecting git+https://github.com/apax-hub/apax.git
>   Cloning https://github.com/apax-hub/apax.git to c:\users\administrator\appdata\local\temp\pip-req-build-4csqz6ih
>   Running command git clone --filter=blob:none --quiet https://github.com/apax-hub/apax.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-4csqz6ih'
>   Resolved https://github.com/apax-hub/apax.git to commit c760b198aa5b9f932261afe344b8af683ae80d92
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting ase<4.0.0,>=3.22.1 (from apax==0.9.1)
>   Using cached ase-3.23.0-py3-none-any.whl.metadata (3.8 kB)
> Collecting clu<0.0.8,>=0.0.7 (from apax==0.9.1)
>   Using cached clu-0.0.7-py3-none-any.whl.metadata (2.0 kB)
> Collecting e3x<2.0.0,>=1.0.2 (from apax==0.9.1)
>   Using cached e3x-1.0.2-py3-none-any.whl.metadata (3.6 kB)
> Collecting einops<0.7.0,>=0.6.0 (from apax==0.9.1)
>   Using cached einops-0.6.1-py3-none-any.whl.metadata (12 kB)
> Collecting flax==0.8.4 (from apax==0.9.1)
>   Using cached flax-0.8.4-py3-none-any.whl.metadata (10 kB)
> Requirement already satisfied: jax<0.5.0,>=0.4.25 in c:\users\administrator\appdata\local\programs\python\python313\lib\site-packages (from apax==0.9.1) (0.4.37)
> Collecting lazy-loader<0.5,>=0.4 (from apax==0.9.1)
>   Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
> Collecting numpy<2.0,>=1.23 (from apax==0.9.1)
>   Using cached numpy-1.26.4.tar.gz (15.8 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting optax<0.2.0,>=0.1.3 (from apax==0.9.1)
>   Using cached optax-0.1.9-py3-none-any.whl.metadata (6.7 kB)
> Collecting orbax-checkpoint==0.5.16 (from apax==0.9.1)
>   Using cached orbax_checkpoint-0.5.16-py3-none-any.whl.metadata (1.8 kB)
> Collecting pydantic<3.0.0,>=2.3.0 (from apax==0.9.1)
>   Using cached pydantic-2.10.3-py3-none-any.whl.metadata (172 kB)
> INFO: pip is looking at multiple versions of apax to determine which version is compatible with other requirements. This could take a while.
> ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9
> ERROR: Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.12.0 (from apax) (from versions: none)
> ERROR: No matching distribution found for tensorflow<3.0.0,>=2.12.0
